!!python/object:jmcomic.jm_option.JmOption
dir_tree: !!python/object:jmcomic.jm_option.DownloadDirTree
  Bd: D:/GitProject/dev/pip/crawler-jmcomic/assets/download/
  flag: Bd_Title_Image
download_convert_image_suffix: .jpg
download_image_then_decode: true
download_multi_thread_photo_batch_count: 20
download_multi_thread_photo_len_limit: 30
download_use_disk_cache: true
filepath: null

client_config:
  domain: jmcomic1.group
  postman_type: cffi
  postman_type_list:
    - requests
    - requests_Session
    - cffi
    - cffi_Session
    - tls_client
  meta_data:
    proxies: null
    allow_redirects: true
    cookies: null
    headers:
      accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
      accept-language: zh-CN,zh;q=0.9
      authority: jmcomic1.rocks
      sec-ch-ua: '"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"'
      sec-ch-ua-mobile: ?0
      sec-ch-ua-platform: '"Windows"'
      sec-fetch-dest: document
      sec-fetch-mode: navigate
      sec-fetch-site: none
      sec-fetch-user: ?1
      upgrade-insecure-requests: '1'
      user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/109.0.0.0 Safari/537.36
